/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    properties: Property;
    agents: Agent;
    amenities: Amenity;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'agent';
  agent?: (number | null) | Agent;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  name: string;
  role?: ('agent' | 'senior_agent' | 'broker' | 'consultant' | 'sales_manager') | null;
  photo?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  whatsapp?: string | null;
  lineId?: string | null;
  facebook?: string | null;
  linkedin?: string | null;
  instagram?: string | null;
  /**
   * Short professional biography (summary)
   */
  bio?: string | null;
  /**
   * Detailed professional background
   */
  fullBio?: string | null;
  licenseNumber?: string | null;
  experienceYears?: number | null;
  languages?:
    | (
        | 'English'
        | 'Thai'
        | 'Mandarin'
        | 'Cantonese'
        | 'Japanese'
        | 'Korean'
        | 'Russian'
        | 'French'
        | 'German'
        | 'Spanish'
      )[]
    | null;
  /**
   * e.g. Sukhumvit, Sathorn, Thong Lo
   */
  serviceAreas?: string[] | null;
  officeAddress?: string | null;
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  /**
   * Property listing title (e.g., "Luxury 3BR House in Sukhumvit")
   */
  title: string;
  /**
   * Name of the housing project or development (e.g., "Casa Ville Rangsit")
   */
  project_name?: string | null;
  status: 'active' | 'pending' | 'sold' | 'rented' | 'inactive';
  listingType: 'sale' | 'rent';
  propertyType: 'condo' | 'house' | 'townhouse' | 'villa' | 'land' | 'commercial' | 'apartment';
  /**
   * Price in THB (Thai Baht)
   */
  price: number;
  /**
   * Full description of the property. Include key features, highlights, and selling points.
   */
  description?: string | null;
  /**
   * Full address for display purposes
   */
  address?: string | null;
  location?: {
    lat?: number | null;
    lng?: number | null;
    province?: string | null;
    district?: string | null;
    sub_district?: string | null;
    postcode?: string | null;
  };
  stats?: {
    bedrooms?: number | null;
    bathrooms?: number | null;
    /**
     * Usable area in square meters
     */
    livingArea?: number | null;
    /**
     * Land size in square wah
     */
    landArea?: number | null;
    floors?: number | null;
    parking?: number | null;
    yearBuilt?: number | null;
  };
  details?: {
    direction?: ('North' | 'South' | 'East' | 'West' | 'Northeast' | 'Northwest' | 'Southeast' | 'Southwest') | null;
    ownership?: ('Freehold' | 'Leasehold' | 'Co-ownership') | null;
    decoration?: ('Fully Furnished' | 'Partially Furnished' | 'Unfurnished' | 'Built-in Only') | null;
    /**
     * Monthly common area maintenance fee per square meter
     */
    common_fee?: number | null;
    /**
     * Allowed for pets (dogs/cats)
     */
    pet_friendly?: boolean | null;
  };
  /**
   * Select which indoor amenities are available
   */
  indoor_amenities?: {
    furniture?: boolean | null;
    air_con?: boolean | null;
    water_heater?: boolean | null;
    digital_lock?: boolean | null;
    bathtub?: boolean | null;
    stove?: boolean | null;
    tv?: boolean | null;
    refrigerator?: boolean | null;
    internet?: boolean | null;
    smart_home?: boolean | null;
  };
  /**
   * Select which project amenities are available
   */
  project_amenities?: {
    lift?: boolean | null;
    parking_facility?: boolean | null;
    pool?: boolean | null;
    gym?: boolean | null;
    cctv?: boolean | null;
    security?: boolean | null;
    garden?: boolean | null;
    storage?: boolean | null;
  };
  /**
   * Add nearby landmarks, transport, schools, hospitals, and shops
   */
  nearby_places?:
    | {
        name: string;
        /**
         * e.g., "2.1 km" or "500 m"
         */
        distance: string;
        category: 'transport' | 'shop' | 'edu' | 'hosp';
        icon?:
          | (
              | 'train'
              | 'car'
              | 'airport'
              | 'mall'
              | 'market'
              | 'supermarket'
              | 'school'
              | 'university'
              | 'hospital'
              | 'clinic'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Main cover image for the listing
   */
  thumbnail?: (number | null) | Media;
  /**
   * YouTube or Vimeo link for virtual tour
   */
  video_url?: string | null;
  images?:
    | {
        image: number | Media;
        tag?:
          | (
              | 'exterior'
              | 'living'
              | 'bedroom'
              | 'kitchen'
              | 'bathroom'
              | 'dining'
              | 'facility'
              | 'floorplan'
              | 'view'
              | 'other'
            )
          | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy amenities relationship (use indoor/project amenities groups instead)
   */
  amenities?: (number | Amenity)[] | null;
  agent?: (number | null) | Agent;
  /**
   * Number of times this listing has been viewed
   */
  view_count?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  name: string;
  /**
   * Lucide icon name (e.g., Wifi, AirVent)
   */
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  message?: string | null;
  status: 'new' | 'contacted' | 'viewing' | 'negotiating' | 'closed_won' | 'closed_lost';
  source?: ('website' | 'facebook' | 'instagram' | 'referral' | 'walkin' | 'other') | null;
  /**
   * The property they inquired about (if any)
   */
  property?: (number | null) | Property;
  /**
   * The agent handling this lead
   */
  agent?: (number | null) | Agent;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  agent?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  title?: T;
  project_name?: T;
  status?: T;
  listingType?: T;
  propertyType?: T;
  price?: T;
  description?: T;
  address?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
        province?: T;
        district?: T;
        sub_district?: T;
        postcode?: T;
      };
  stats?:
    | T
    | {
        bedrooms?: T;
        bathrooms?: T;
        livingArea?: T;
        landArea?: T;
        floors?: T;
        parking?: T;
        yearBuilt?: T;
      };
  details?:
    | T
    | {
        direction?: T;
        ownership?: T;
        decoration?: T;
        common_fee?: T;
        pet_friendly?: T;
      };
  indoor_amenities?:
    | T
    | {
        furniture?: T;
        air_con?: T;
        water_heater?: T;
        digital_lock?: T;
        bathtub?: T;
        stove?: T;
        tv?: T;
        refrigerator?: T;
        internet?: T;
        smart_home?: T;
      };
  project_amenities?:
    | T
    | {
        lift?: T;
        parking_facility?: T;
        pool?: T;
        gym?: T;
        cctv?: T;
        security?: T;
        garden?: T;
        storage?: T;
      };
  nearby_places?:
    | T
    | {
        name?: T;
        distance?: T;
        category?: T;
        icon?: T;
        id?: T;
      };
  thumbnail?: T;
  video_url?: T;
  images?:
    | T
    | {
        image?: T;
        tag?: T;
        caption?: T;
        id?: T;
      };
  amenities?: T;
  agent?: T;
  view_count?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  phone?: T;
  email?: T;
  whatsapp?: T;
  lineId?: T;
  facebook?: T;
  linkedin?: T;
  instagram?: T;
  bio?: T;
  fullBio?: T;
  licenseNumber?: T;
  experienceYears?: T;
  languages?: T;
  serviceAreas?: T;
  officeAddress?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  source?: T;
  property?: T;
  agent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}