/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgSchema,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const db_schema = pgSchema('payload')
export const enum_users_role = db_schema.enum('enum_users_role', ['admin', 'agent'])
export const enum_properties_status = db_schema.enum('enum_properties_status', [
  'active',
  'pending',
  'sold',
  'inactive',
])
export const enum_properties_listing_type = db_schema.enum('enum_properties_listing_type', [
  'sale',
  'rent',
])
export const enum_properties_property_type = db_schema.enum('enum_properties_property_type', [
  'condo',
  'house',
  'land',
  'villa',
])

export const users_sessions = db_schema.table(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = db_schema.table(
  'users',
  {
    id: serial('id').primaryKey(),
    role: enum_users_role('role').notNull().default('agent'),
    agent: integer('agent_id').references(() => agents.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_agent_idx').on(columns.agent),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = db_schema.table(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const properties_images = db_schema.table(
  'properties_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('properties_images_order_idx').on(columns._order),
    index('properties_images_parent_id_idx').on(columns._parentID),
    index('properties_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [properties.id],
      name: 'properties_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const properties = db_schema.table(
  'properties',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    status: enum_properties_status('status').notNull().default('active'),
    listingType: enum_properties_listing_type('listing_type').notNull().default('sale'),
    propertyType: enum_properties_property_type('property_type').notNull(),
    price: numeric('price', { mode: 'number' }).notNull(),
    description: jsonb('description'),
    address: varchar('address'),
    location_lat: numeric('location_lat', { mode: 'number' }),
    location_lng: numeric('location_lng', { mode: 'number' }),
    stats_bedrooms: numeric('stats_bedrooms', { mode: 'number' }),
    stats_bathrooms: numeric('stats_bathrooms', { mode: 'number' }),
    stats_livingArea: numeric('stats_living_area', { mode: 'number' }),
    stats_landArea: numeric('stats_land_area', { mode: 'number' }),
    stats_yearBuilt: numeric('stats_year_built', { mode: 'number' }),
    thumbnail: integer('thumbnail_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    agent: integer('agent_id').references(() => agents.id, {
      onDelete: 'set null',
    }),
    featured: boolean('featured').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('properties_thumbnail_idx').on(columns.thumbnail),
    index('properties_agent_idx').on(columns.agent),
    index('properties_updated_at_idx').on(columns.updatedAt),
    index('properties_created_at_idx').on(columns.createdAt),
  ],
)

export const properties_rels = db_schema.table(
  'properties_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    amenitiesID: integer('amenities_id'),
  },
  (columns) => [
    index('properties_rels_order_idx').on(columns.order),
    index('properties_rels_parent_idx').on(columns.parent),
    index('properties_rels_path_idx').on(columns.path),
    index('properties_rels_amenities_id_idx').on(columns.amenitiesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [properties.id],
      name: 'properties_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['amenitiesID']],
      foreignColumns: [amenities.id],
      name: 'properties_rels_amenities_fk',
    }).onDelete('cascade'),
  ],
)

export const agents = db_schema.table(
  'agents',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    photo: integer('photo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    phone: varchar('phone'),
    email: varchar('email'),
    lineId: varchar('line_id'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('agents_photo_idx').on(columns.photo),
    index('agents_updated_at_idx').on(columns.updatedAt),
    index('agents_created_at_idx').on(columns.createdAt),
  ],
)

export const amenities = db_schema.table(
  'amenities',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    icon: varchar('icon'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('amenities_updated_at_idx').on(columns.updatedAt),
    index('amenities_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = db_schema.table(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = db_schema.table(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = db_schema.table(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    propertiesID: integer('properties_id'),
    agentsID: integer('agents_id'),
    amenitiesID: integer('amenities_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_properties_id_idx').on(columns.propertiesID),
    index('payload_locked_documents_rels_agents_id_idx').on(columns.agentsID),
    index('payload_locked_documents_rels_amenities_id_idx').on(columns.amenitiesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['propertiesID']],
      foreignColumns: [properties.id],
      name: 'payload_locked_documents_rels_properties_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['agentsID']],
      foreignColumns: [agents.id],
      name: 'payload_locked_documents_rels_agents_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['amenitiesID']],
      foreignColumns: [amenities.id],
      name: 'payload_locked_documents_rels_amenities_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = db_schema.table(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = db_schema.table(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = db_schema.table(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  agent: one(agents, {
    fields: [users.agent],
    references: [agents.id],
    relationName: 'agent',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_properties_images = relations(properties_images, ({ one }) => ({
  _parentID: one(properties, {
    fields: [properties_images._parentID],
    references: [properties.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [properties_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_properties_rels = relations(properties_rels, ({ one }) => ({
  parent: one(properties, {
    fields: [properties_rels.parent],
    references: [properties.id],
    relationName: '_rels',
  }),
  amenitiesID: one(amenities, {
    fields: [properties_rels.amenitiesID],
    references: [amenities.id],
    relationName: 'amenities',
  }),
}))
export const relations_properties = relations(properties, ({ one, many }) => ({
  thumbnail: one(media, {
    fields: [properties.thumbnail],
    references: [media.id],
    relationName: 'thumbnail',
  }),
  images: many(properties_images, {
    relationName: 'images',
  }),
  agent: one(agents, {
    fields: [properties.agent],
    references: [agents.id],
    relationName: 'agent',
  }),
  _rels: many(properties_rels, {
    relationName: '_rels',
  }),
}))
export const relations_agents = relations(agents, ({ one }) => ({
  photo: one(media, {
    fields: [agents.photo],
    references: [media.id],
    relationName: 'photo',
  }),
}))
export const relations_amenities = relations(amenities, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    propertiesID: one(properties, {
      fields: [payload_locked_documents_rels.propertiesID],
      references: [properties.id],
      relationName: 'properties',
    }),
    agentsID: one(agents, {
      fields: [payload_locked_documents_rels.agentsID],
      references: [agents.id],
      relationName: 'agents',
    }),
    amenitiesID: one(amenities, {
      fields: [payload_locked_documents_rels.amenitiesID],
      references: [amenities.id],
      relationName: 'amenities',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  db_schema: typeof db_schema
  enum_users_role: typeof enum_users_role
  enum_properties_status: typeof enum_properties_status
  enum_properties_listing_type: typeof enum_properties_listing_type
  enum_properties_property_type: typeof enum_properties_property_type
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  properties_images: typeof properties_images
  properties: typeof properties
  properties_rels: typeof properties_rels
  agents: typeof agents
  amenities: typeof amenities
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_properties_images: typeof relations_properties_images
  relations_properties_rels: typeof relations_properties_rels
  relations_properties: typeof relations_properties
  relations_agents: typeof relations_agents
  relations_amenities: typeof relations_amenities
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
